services:
  mysql:
    image: mysql:latest
    env_file: ./env/mysql.env
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    container_name: app
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
