name: Deploy Application Monitor

on:
  push:
    branches: [main]


jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Java
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '21'
       - name: Build project
         run: mvn clean install -DskipTests -Dmaven.test.skip=true
       - name: Login Docker Hub
         run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
       - name: Build docker image
         run: docker build -t mmsnb/monitor-habitos-empresa .
       - name: Push image docker
         run: docker push mmsnb/monitor-habitos-empresa

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create env folder
        run: |
          mkdir -p env
          touch env/app.env
          touch env/mysql.env
      - name: Remove docker container
        run: |
          # Parar e remover todos os contêineres
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true

          # Remover todas as imagens
          docker rmi $(docker images -q) -f || true

          # Remover todos os volumes
          docker volume rm $(docker volume ls -q) || true

          # Remover redes personalizadas (ignorar as redes padrão)
          docker network rm $(docker network ls -q --filter type=custom) || true

          # Limpeza geral para remover recursos pendentes
          docker system prune -a --volumes -f || true
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Pull image from docker hub
        run: docker pull mmsnb/monitor-habitos-empresa:latest
      - name: Run docker-compose
        run: docker compose up -d






