name: Deploy Application Monitor

on:
  push:
    branches: [main]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Java
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '21'
       - name: Build project
         run: mvn clean install -DskipTests -Dmaven.test.skip=true
       - name: Login Docker Hub
         run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
       - name: Build docker image
         run: docker build -t mmsnb/monitor-habitos .
       - name: Push image docker
         run: docker push mmsnb/monitor-habitos



