name: Deploy Application Monitor

on:
  push:
    branches: [main]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Java
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '21'
       - name: Build project
         run: mvn clean install -DskipTests -Dmaven.test.skip=true
       - name: Login Docker Hub
         run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
       - name: Build docker image
         run: docker build -t mmsnb/monitor-habitos-empresa .
       - name: Push image docker
         run: docker push mmsnb/monitor-habitos-empresa





  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Se precisar do código no servidor de deploy, adicione o checkout aqui

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Pull image from docker hub
        run: docker pull mmsnb/monitor-habitos-empresa:latest

      - name: Remove docker container if exists
        run: |
          docker ps -q -f name=deploy_ghactions | xargs -r docker rm -f

      - name: Run docker container with docker-compose
        run: |
          cd /path/to/your/docker-compose/directory  # Garanta que o caminho esteja correto
          docker-compose up -d --build