name: Deploy Application Monitor

on:
  push:
    branches: [main]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull mmsnb/monitor-habitos-empresa:latest
      - name: Remove docker container
        run: docker rm -f deploy_ghactions
      - name: Run docker container
        run: docker-compose up --build